name: Generation Tippecanoe Dynamique

on:
  workflow_dispatch:
    inputs:
      geojson_filename:
        description: 'Nom du fichier GeoJSON à compiler'
        required: true
        default: 'data.geojson'

jobs:
  build-mbtiles:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev zlib1g-dev

      - name: Compiler Tippecanoe
        run: |
          git clone https://github.com/felt/tippecanoe.git
          cd tippecanoe
          make -j$(nproc)
          sudo make install

      - name: Générer le fichier MBTiles
        run: |
          # Utilisation de l'input envoyé par Python
          tippecanoe -o result.mbtiles "${{ github.event.inputs.geojson_filename }}"

      - name: Sauvegarder le résultat
        uses: actions/upload-artifact@v4
        with:
          name: mes-tuiles-mbtiles
          path: ./result.mbtiles
