name: Generation Tippecanoe Multi-Fichiers

on:
  workflow_dispatch: # Plus besoin d'inputs ici, le script Python dépose les fichiers directement

jobs:
  build-mbtiles:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer les dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev zlib1g-dev

      - name: Compiler Tippecanoe
        run: |
          git clone https://github.com/felt/tippecanoe.git
          cd tippecanoe
          make -j$(nproc)
          sudo make install

      # Vérification visuelle des fichiers reçus dans les logs GitHub
      - name: Lister les fichiers GeoJSON reçus
        run: ls -la *.geojson

      # Tippecanoe fusionne automatiquement tous les .geojson trouvés
      - name: Générer le fichier MBTiles global
        run: |
          tippecanoe -o result.mbtiles *.geojson

      - name: Sauvegarder le résultat
        uses: actions/upload-artifact@v4
        with:
          name: mes-tuiles-mbtiles
          path: ./result.mbtiles
